"""Generates backlinks.md, tags.md, index.md, and internal/registry.md."""

from pathlib import Path

from .page import WikiDatabase, WikiPage


def _latest_page_date(db: WikiDatabase) -> str:
    dates = [value for page in db.pages.values() if isinstance(value := page.frontmatter.get("updated"), str)]
    return max(dates, default="1970-01-01")


def generate_backlinks(db: WikiDatabase, wiki_dir: Path) -> Path:
    """Builds wiki/backlinks.md detailing all incoming wikilinks per page with YAML frontmatter."""
    backlinks: dict[str, set[str]] = {}

    for page in db.pages.values():
        for link in page.wikilinks:
            resolved = db.resolve_link(link)
            target_title = resolved.title if resolved else link
            backlinks.setdefault(target_title, set()).add(page.title)

    updated = _latest_page_date(db)
    lines = [
        "---",
        'title: "Wiki Backlinks"',
        "type: index",
        "scope: global",
        f"updated: {updated}",
        "---",
        "",
        "# Backlinks Index",
        "",
        "_Auto-generated by `wiki gen`. Do not edit by hand._",
        "",
    ]

    for target_title in sorted(backlinks.keys(), key=lambda s: s.lower()):
        sources = sorted(backlinks[target_title], key=lambda s: s.lower())
        if not sources:
            continue
        lines.append(f"## [[{target_title}]]")
        for src in sources:
            lines.append(f"- [[{src}]]")
        lines.append("")

    content = "\n".join(lines).strip() + "\n"
    out_file = wiki_dir / "backlinks.md"
    out_file.write_text(content, encoding="utf-8")
    return out_file


def generate_tags(db: WikiDatabase, wiki_dir: Path) -> Path:
    """Builds wiki/tags.md grouping pages by tag with YAML frontmatter."""
    tag_map: dict[str, list[WikiPage]] = {}

    for page in db.pages.values():
        for tag in page.tags:
            tag_map.setdefault(tag, []).append(page)

    updated = _latest_page_date(db)
    lines = [
        "---",
        'title: "Wiki Tags"',
        "type: index",
        "scope: global",
        f"updated: {updated}",
        "---",
        "",
        "# Tags Index",
        "",
        "_Auto-generated by `wiki gen`. Do not edit by hand._",
        "",
    ]

    for tag in sorted(tag_map.keys(), key=lambda s: s.lower()):
        pages = sorted(tag_map[tag], key=lambda p: p.title.lower())
        lines.append(f"## #{tag}")
        for page in pages:
            lines.append(f"- [[{page.title}]]")
        lines.append("")

    content = "\n".join(lines).strip() + "\n"
    out_file = wiki_dir / "tags.md"
    out_file.write_text(content, encoding="utf-8")
    return out_file


def generate_index(db: WikiDatabase, wiki_dir: Path) -> Path:
    """Builds wiki/index.md from page frontmatter, preserving any hand-maintained ## Backlog block."""
    out_file = wiki_dir / "index.md"

    # Extract existing ## Backlog block if present
    backlog_text = ""
    if out_file.is_file():
        existing_text = out_file.read_text(encoding="utf-8")
        if "## Backlog" in existing_text:
            backlog_text = "## Backlog" + existing_text.split("## Backlog", 1)[1]

    entities: list[WikiPage] = []
    concepts: list[WikiPage] = []
    syntheses: list[WikiPage] = []
    projects: list[WikiPage] = []

    for page in sorted(db.pages.values(), key=lambda p: p.title.lower()):
        if page.filepath.name.lower() in (
            "index.md",
            "log.md",
            "backlinks.md",
            "tags.md",
            "conventions.md",
            "scaling.md",
        ):
            continue

        parent_folder = page.filepath.parent.name.lower()
        p_type = str(page.frontmatter.get("type", "")).lower()

        if page.scope == "project" or parent_folder == "projects":
            projects.append(page)
        elif parent_folder == "entities" or p_type == "entity":
            entities.append(page)
        elif parent_folder == "concepts" or p_type == "concept":
            concepts.append(page)
        elif parent_folder == "syntheses" or p_type == "synthesis":
            syntheses.append(page)
        else:
            concepts.append(page)

    updated = _latest_page_date(db)
    lines = [
        "---",
        'title: "Wiki Catalog"',
        "type: index",
        "scope: global",
        f"updated: {updated}",
        "---",
        "",
        "# Wiki Catalog",
        "",
        "_Auto-generated by `wiki gen`. Do not edit by hand._",
        "",
    ]

    sections = [
        ("Entities", entities),
        ("Concepts", concepts),
        ("Syntheses", syntheses),
        ("Projects & Systems", projects),
    ]

    for title, pages in sections:
        lines.append(f"## {title}")
        if not pages:
            lines.append("*No pages yet.*")
        else:
            for p in pages:
                sum_str = f" — {p.summary}" if p.summary else ""
                lines.append(f"- [[{p.title}]]{sum_str}")
        lines.append("")

    if backlog_text.strip():
        lines.append(backlog_text.strip())
        lines.append("")

    content = "\n".join(lines).strip() + "\n"
    out_file.write_text(content, encoding="utf-8")
    return out_file


def generate_registry(repo_root: Path) -> Path:
    """Generates internal/registry.md from agent skills and reusable prompts."""
    internal = repo_root / "internal"
    out_file = internal / "registry.md"

    skill_files = sorted((internal / "skills").glob("*/SKILL.md")) if (internal / "skills").is_dir() else []
    prompt_files = sorted((internal / "prompts").glob("*.md")) if (internal / "prompts").is_dir() else []

    lines = [
        "# Company Capabilities Registry",
        "",
        "_Auto-generated by `wiki gen`. Do not edit by hand._",
        "",
        "## Internal Skills",
        "_Source-of-truth in `internal/skills/`; synced to each agent by `wiki install`._",
        "",
    ]

    for f in skill_files:
        page = WikiPage(f)
        description = page.frontmatter.get("description", "")
        desc = f" — {description}" if isinstance(description, str) and description else ""
        lines.append(f"- **{f.parent.name}**{desc}  `{f.relative_to(repo_root)}`")

    lines.extend(["", "## Prompts", "_Reusable templates; pull on request._", ""])
    for f in prompt_files:
        page = WikiPage(f)
        lines.append(f"- **{page.title}** — `{f.relative_to(repo_root)}`")

    lines.append("")
    new_content = "\n".join(lines)

    if out_file.is_file():
        existing = out_file.read_text(encoding="utf-8")
        if existing.strip() == new_content.strip():
            return out_file

    out_file.parent.mkdir(exist_ok=True, parents=True)
    out_file.write_text(new_content, encoding="utf-8")
    return out_file
